spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
---
spring:
  profiles:
    active: local
  data:
    redis:
      port: 6379
      host: localhost